
version: "3.8"

services:
  app:
    # Add an explicit image name. Replace with your Docker Hub username.
    image: lanciere/Edu-app:latest
    build: .
    ports:
      - "8070:8070"
      - "5174:5174"
    # The env_file path is updated to match the location from setup.sh
    env_file:
      - ./env/.env
    restart: unless-stopped
    # The volume mount '.:/app' has been removed. It's suitable for development
    # with live-reloading but conflicts with a multi-stage production build,
    # as it overwrites the optimized application code inside the container.

    # Enable GPU access for the container.
    # This requires the NVIDIA Container Toolkit to be installed on the host.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
